### ISSUE TITLE
Display match totals

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/libretro-thumbnails-check#2]
- Total Boxarts missing
- Total Snaps missing
- Total Titles missing
- Total pics missing

**Comment by lasers** [comment]
How will you differentiate between Total Boxarts missing and Total Boxarts missing-on-purpose? Bunch of Beta/Proto was recently deleted for Genesis Boxarts.

**Comment by RobLoach** [comment]
> Total Boxarts missing-on-purpose? 

Not sure! Have any ideas? Any other metrics you think we could show?

**Comment by lasers** [comment]
I prefer that they maintain mockup/fake arts because I do have (Beta), (Proto), and some other roms that was still in the database... Many others does too... and it's easier to work with.

If it's a problem for some, we could opt for virtual mockup arts... Not hiding the fact that the boxarts for the said games does not exist, but then it would mean more work... Making custom artworks... etc.

With this route, we wouldn't really have to worry about anything and know that there should be always the same numbers for all three folders.

Plus the guys who opted for boxarts over snaps and titles shouldn't deal with missing thumbnails because they opted for default choice (boxarts). I myself like boxarts over snaps and titles. Anyway...

Possible metrics
* Total Boxarts / Total Boxarts missing
* Total Snaps / Total Snaps missing
* Total Titles / Total Titles missing
* Total Pics / Total Pics missing
*
* Total Orphans / Total non-PNG (*.txt)

**Comment by lasers** [comment]
Total Usage Space ~~/Total Space Usage missing~~

**Comment by lasers** [comment]
The align looks slightly off. Remove space on left column or add space on right column?

**Comment by RobLoach** [comment]
Have an example?

**Comment by lasers** [comment]
```
RobLoach (Canada) ✗      ✓     ✓
RobLoach (Canada) ✗ (6)  ✓ (5) ✓
```

**Comment by lasers** [comment]
[lasers/libretro-database/tree/thumbnails-check](https://github.com/lasers/libretro-database/tree/thumbnails-check) 🚗 🚬 

EDIT: I think it would be nice to put orphaned files in before nothumbnails in regular files to get rid of orphaned files too (ha ha, irony) as many orphans files only have 1 line inside.

**Comment by RobLoach** [comment]
Had it as one Markdown file before, but it was too large:
https://github.com/RobLoach/libretro-thumbnails-check/blob/7d9cc27da688c502cf1c8ff0627fc77ed1b15f09/report.md

Switching back to markdown might be a good option, since they're individual files now. A Table might work:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables
